name: cse583
channels:
  - pytorch
  - defaults
dependencies:
  - astroid=2.11.7
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - dill=0.3.6
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - flit-core=3.6.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=68.1
  - idna=3.4
  - isort=5.9.3
  - joblib=1.1.1
  - jpeg=9e
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.1
  - libopenblas=0.3.21
  - libopus=1.3
  - libpng=1.6.37
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - mccabe=0.7.0
  - ncurses=6.3
  - nettle=3.7.3
  - numexpr=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openh264=1.8.0
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.2
  - pillow=9.2.0
  - pip=22.2.2
  - platformdirs=2.5.2
  - pycparser=2.21
  - pylint=2.14.5
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - pytorch=1.13.0
  - pytz=2022.1
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.11.1
  - torchvision=0.14.0
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.12
  - wheel=0.37.1
  - wrapt=1.14.1
  - x264=1!152.20180806
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.2
prefix: /opt/anaconda3/envs/cse583
